name: release

on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Action
        uses: mesopelagique/build-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      - name: env
        run: |
          echo $GITHUB_EVENT_PATH
          RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
          echo $RELEASE_ID
          echo $GITHUB_WORKPATH
